-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- List the number of films per category.
USE sakila;

SELECT 
    c.name AS category,
    COUNT(fc.film_id) AS film_count
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY film_count DESC;

-- Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store AS s
JOIN address AS a ON s.address_id = a.address_id
JOIN city AS ci ON a.city_id = ci.city_id
JOIN country AS co ON ci.country_id = co.country_id;
-- Calculate the total revenue generated by each store in dollars.
SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st
    ON s.store_id = st.store_id
JOIN payment AS p
    ON st.staff_id = p.staff_id
GROUP BY s.store_id
ORDER BY total_revenue DESC;

-- Determine the average running time of films for each category.

SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY  average_running_time DESC;

-- Bonus:
-- Identify the film categories with the longest average running time.

SELECT 
    c.name AS category_longest_average_time,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC
LIMIT 1;

-- Display the top 10 most frequently rented movies in descending order.

SELECT 
	 f.film_id,
     f.title AS film,
     COUNT(r.rental_id) AS rental_count
FROM rental AS r
JOIN inventory AS i
    ON r.inventory_id = i.inventory_id
JOIN film AS f
    ON i.film_id = f.film_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 10;
-- Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT 
    f.title,
    CASE 
        WHEN IFNULL(COUNT(i.inventory_id), 0) = 0 
            THEN 'NOT available'
        ELSE 'Available'
    END AS disponibilidad
FROM film f
LEFT JOIN inventory i 
    ON f.film_id = i.film_id
    AND i.store_id = 1
WHERE title = "Academy Dinosaur"  
GROUP BY f.title
ORDER BY f.title;
-- Provide a list of all distinct film titles, along with their availability status in the inventory.
 -- Include a column indicating whether each title is 'Available' or 'NOT available.
 -- Note that there are 42 titles that are not in the inventory, and this information 
 -- can be obtained using a CASE statement combined with IFNULL."
SELECT 
    f.title,
    COUNT(i.inventory_id) AS total_copias,
    CASE 
        WHEN IFNULL(COUNT(i.inventory_id), 0) = 0 
            THEN 'NOT available'
        ELSE 'Available'
    END AS disponibilidad
FROM film f
LEFT JOIN inventory i 
    ON f.film_id = i.film_id
GROUP BY f.title
ORDER BY f.title;
